name: App
options:
  bundleIdPrefix: earth.levi.listsss
targets:
  App:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources: Source
    dependencies:      
      - package: Wendy
    settings:
      GENERATE_INFOPLIST_FILE: YES
packages:
  Wendy:
    url: https://github.com/levibostian/Wendy-iOS.git 
    majorVersion: 9.0.1
    